### ISSUE TITLE
A bit of documentation?

### ISSUE THREAD

**Issue by jgm-ktg** [casbin/casbin-dashboard#1]
Hi, was redirected here from web-ui issue.  New to go and to this project.  How do I run the dashboard locally?

**Comment by jgm-ktg** [comment]
I did a `go get github.com/casbin/casbin-dashboard`
then `~/go/bin/casbin-dashboard` from `~/go/src/github.com/casbin/casbin-dashboard` to pick up the conf with a local mysql root pwd of 123

I can hit some of the endpoints at 8000 and `yarn start` in `web` hits them too, but fails with 

```./src/AdapterTable.js
Attempted import error: 'DownOutlined' is not exported from '@ant-design/icons'.
```

**Comment by jgm-ktg** [comment]
Fixed the import error, I think via `yarn add @ant-design/icons@4.0.0-rc.0`

**Comment by jgm-ktg** [comment]
Hello again... now that I think I have it running, I don't see anything like PolicyEditor.html from the web-ui ... seems like the scope of this dashboard is different?  How do I set up a web UI for managing policies?  (With a Postgres back end for storing the policies, ideally, and with casbin-server)

**Comment by hsluoyz** [comment]
Hi @jgm-ktg , we will develop these functionalities these days.

**Comment by hsluoyz** [comment]
We have policy editor now, see: https://dashboard.casbin.org/adapter/adapter_1

**Comment by jgm-ktg** [comment]
![Screen Shot 2020-02-04 at 10 30 40 AM](https://user-images.githubusercontent.com/40578731/73765319-fe194b80-4739-11ea-8eb5-44042e554644.png)
@hsluoyz these links don't work on that page, fyi

**Comment by hsluoyz** [comment]
Hi @jgm-ktg 

You are supposed to click the `edit` buttons of the `Home` page to enter other tabs, not click them directly.

![image](https://user-images.githubusercontent.com/3787410/73801882-cfad7600-47f6-11ea-92d0-cbc3f55328f6.png)

**Comment by jgm-ktg** [comment]
Yes, but it seems like the links at the top should do something?  They don't appear to be functional

**Comment by hsluoyz** [comment]
It has been fixed: https://github.com/casbin/casbin-dashboard/commit/b0d12da8dcd7ea5db5a3c65ae36af771cbe715c1
