### ISSUE TITLE
Update Readme 

### ISSUE THREAD

**Issue by aryamanpuri** [casbin/casbin-dashboard#10]
Instead of using React Boilerplate Readme, 
we should use write manual Readme consisting of how to setup and start the project .

**Comment by 6ecuk** [comment]
Any updates here? I tried setup localy project and got alot errors in console log...

**Comment by hsluoyz** [comment]
@BetaCat0 @438561537 can you take this issue?

**Comment by hsluoyz** [comment]
@6ecuk what error did you encounter?

**Comment by 438561537** [comment]
@hsluoyzYes. I can.
 @6ecuk @aryamanpuriWhat problems did you encounter when you started the project?

**Comment by 6ecuk** [comment]
Hi, I tried to build a web part in docker. 
>FROM node:14-alpine3.12
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
ADD ./web web
WORKDIR ./web
RUN npm install
ENTRYPOINT [ "npm", "start"]

And console.log in browser I got errors

> Warning: React does not recognize the `inlineIndent` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `inlineindent` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
Warning: React does not recognize the `renderMenuItem` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `rendermenuitem` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by 438561537** [comment]
@6ecuk Thanks for your mentioned！To fix this warning, I recommend to delete this text.https://github.com/casbin/casbin-dashboard/blob/e2297653afdb4c8c10d100c5c70ecf36407b8775/web/src/App.js#L57
we should't put any text under the <menu> and we just could only put the Menu.item under the Menu directly.[link](https://github.com/ant-design/ant-design/issues/8708).

**Comment by 6ecuk** [comment]
@438561537 also in a service log

> web@0.1.0 start /web
> set PORT=3030 && react-scripts start
> 
> Starting the development server...
> 
> Compiled with warnings.
> 
> ./src/App.js
>   Line 67:25:    The href attribute requires a valid value to be accessible. Provide a valid, navigable address as the href value. If you cannot provide a valid href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid
>   Line 75:25:    The href attribute requires a valid value to be accessible. Provide a valid, navigable address as the href value. If you cannot provide a valid href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid
>   Line 83:25:    The href attribute requires a valid value to be accessible. Provide a valid, navigable address as the href value. If you cannot provide a valid href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid
>   Line 89:24:    Using target="_blank" without rel="noopener noreferrer" is a security risk: see https://mathiasbynens.github.io/rel-noopener                                                                                                                                                                                                                                      react/jsx-no-target-blank
>   Line 112:23:   Emojis should be wrapped in <span>, have role="img", and have an accessible description with aria-label or aria-labelledby                                                                                                                                                                                                                                        jsx-a11y/accessible-emoji
>   Line 112:128:  Using target="_blank" without rel="noopener noreferrer" is a security risk: see https://mathiasbynens.github.io/rel-noopener                                                                                                                                                                                                                                      react/jsx-no-target-blank
> 
> Search for the keywords to learn more about each warning.
> To ignore, add // eslint-disable-next-line to the line before.

**Comment by 6ecuk** [comment]
> @6ecuk Thanks for your mentioned！To fix these warnings, I recommend to delete this text.
> 
> https://github.com/casbin/casbin-dashboard/blob/e2297653afdb4c8c10d100c5c70ecf36407b8775/web/src/App.js#L57
> 
> we should't put any text under the menu and we just could only put the Menu.item under the Menu directly.[link](https://github.com/ant-design/ant-design/issues/8708).

After deleting, i got this 
![изображение](https://user-images.githubusercontent.com/8338314/87321326-c908f480-c534-11ea-8716-669d11277b76.png)

**Comment by 438561537** [comment]
@6ecuk I have noticed these problems.  It need to fix some small detail in app.js. I will make a pr to fix these as soon as possible.Thanks!

**Comment by 6ecuk** [comment]
Thanks

**Comment by 6ecuk** [comment]
@438561537 I tried your fixes from the pull request.  Errors in service log fixed, but I still have 
![изображение](https://user-images.githubusercontent.com/8338314/87418050-c2808880-c5d9-11ea-82ac-0fe20e07e7a0.png)

**Comment by 438561537** [comment]
@6ecuk Hello, I have modified the pr and now you can run the dashboard without fatal errors.  Actually there are some problems in other js files(not App.js), which will lead to some warnings like the picture below. I will modify these files and make pr as soon as possible. 
![20200714](https://user-images.githubusercontent.com/41043187/87426142-5caff300-c611-11ea-8335-3b6d6a7c2f5f.png)
As for futhure enhancement, this dashboard Repository might be totally modify for better interaction. Sincerely welcome to give us some constructive suggestions in the future.

**Comment by 6ecuk** [comment]
At last, I ran the front part, small victory. Additional constructive suggestion. Currently, if no rows in the database, interface not show any of models, adapters, enforcers and you can't add init rows from the interface.

**Comment by 438561537** [comment]
@6ecuk Yes, Just as you mentioned, the dashboard needs to improved in these aspects. 
First, we need to fix the bugs(include Delete action, Edit action) in this repository. 
Second, we need to improve the UI to make the dashboard look better.
And thirdly, we shoud add some new features(like Add init rows from the interface, Casbin model syntax and semantics check.....) for future enhancement.
Thank you for you advice!

**Comment by hsluoyz** [comment]
Let's focus on this issue. Is it got fixed?

**Comment by hsluoyz** [comment]
If yes, please close it.

**Comment by 438561537** [comment]
@hsluoyz As for the bugs in App.js, it has got fixed. There are some small bugs in other files. we can close this issue and fix other files for a new issue.
