### ISSUE TITLE
On multiple clicks on moveup toast message is displayed

### ISSUE THREAD

**Issue by arteevraina** [casbin/casbin-dashboard#121]
### Screenshot
![casbin1](https://user-images.githubusercontent.com/43968121/92997271-ad6b9b80-f52f-11ea-86f3-3713b06e366a.png)

### Expected Behaviour
Toast Message should be displayed only if there is no toast message being displayed.

**Comment by hsluoyz** [comment]
@arteevraina can you fix it?

/cc @BetaCat0 @GopherJ @438561537

**Comment by arteevraina** [comment]
> @arteevraina can you fix it?
> 
> /cc @BetaCat0 @GopherJ @438561537 

Sure thing!
