### ISSUE TITLE
Submit button not aligned properly

### ISSUE THREAD

**Issue by SingingApple** [casbin/casbin-dashboard#125]
### Add New Policy Form
Submit button is not aligned properly.

![image](https://user-images.githubusercontent.com/39864404/93373127-8801c900-f872-11ea-892a-63db9a832885.png)

**Comment by hsluoyz** [comment]
Can anyone make a PR?

**Comment by pranav1698** [comment]
@hsluoyz are you working on this issue?

**Comment by hsluoyz** [comment]
Not yet actually.

**Comment by pranav1698** [comment]
@hsluoyz can i work on it?

**Comment by pranav1698** [comment]
![Screenshot from 2021-01-06 23-38-35](https://user-images.githubusercontent.com/34754265/103804597-65d9c400-5078-11eb-8b3a-ad2b7e88f958.png)
Does this look good?

**Comment by hsluoyz** [comment]
@pranav1698 looks good. Can you make a PR?
