### ISSUE TITLE
Register Button takes no where

### ISSUE THREAD

**Issue by MehtaManan07** [casbin/casbin-dashboard#132]
The "register now" button on the login page takes the user nowhere. I would like to fix that thing, but where should it take the user exactly??

**Comment by hsluoyz** [comment]
@BetaCat0 @438561537

**Comment by 438561537** [comment]
@MehtaManan07 The repository has updated, and you can login with your github account and without register.

**Comment by hsluoyz** [comment]
Confirmed it has been fixed, see: https://dashboard.casbin.org/
