### ISSUE TITLE
Casbin dashboard UI inconsistency in the running port and authentication problem

### ISSUE THREAD

**Issue by mteodor** [casbin/casbin-dashboard#140]
What is supposed to be running port ?
It starts on 3000, but when authentication against github is performed it redirects to `http://localhost:3030/callback`
When I changed all references of 3030 to 3000 it seems that it works fine, however there is a problem in the authorization flow
It seems that `https://api.github.com/user/emails` requires that token is in the authorization header

**Comment by mteodor** [comment]
Authentication problem will be resolved with https://github.com/casbin/casbin-dashboard/pull/139
However ports are not consistent in the web app.

**Comment by hsluoyz** [comment]
@mteodor If you are not using Windows, you probably start with wrong port: 3000. In this case, you need to change the following code to use port: 3030

https://github.com/casbin/casbin-dashboard/blob/6a0b240226ff173030c632594adad8f134e14f4f/web/package.json#L18-L24
