### ISSUE TITLE
Realignment of submit buttons on each form page (Add Model, Add Adapter, Add Enforcer) 

### ISSUE THREAD

**Issue by pranav1698** [casbin/casbin-dashboard#143]
The submit button is not aligned all of the forms in the casbin-dashboard like (Add Model, Add Adapter, Add Enforcer)
![Screenshot from 2021-01-15 02-02-42](https://user-images.githubusercontent.com/34754265/104645921-c64eae00-56d5-11eb-9d4d-0503112fd0d0.png)
![Screenshot from 2021-01-15 02-02-59](https://user-images.githubusercontent.com/34754265/104645947-cfd81600-56d5-11eb-9d86-2b06cdbb30fd.png)

This is an extension to #142

**Comment by hsluoyz** [comment]
Where is PR?

**Comment by pranav1698** [comment]
@hsluoyz I will be happy to work on it
