### ISSUE TITLE
Nested scrollbars in the app

### ISSUE THREAD

**Issue by nik72619c** [casbin/casbin-dashboard#24]
#### Current behaviour
When a list of items become large, a scrollbar appears for that list item . This creates a somewhat bad UX according to me. 

Also, since pagination is applied here I feel that the scrollbar for should not be there at all

@hsluoyz Please let me know if I shall take this forward :)
Working on this one

**Comment by hsluoyz** [comment]
Show pictures.

**Comment by techguybiswa** [comment]
Hi @hsluoyz ,

I am attaching a picture of what I observed.

<img src="https://i.ibb.co/2kWTKG0/Screenshot-2020-03-24-at-2-27-28-PM.png"/>

So as you can see when I add a large number of rows the table becomes scrollable.
Also we have an. already existing pagination.

So either we can :

1. Remove pagination and make it scrollable
2 Or remove scroll and make it paginated.

If nothing is done then the UI/UX, in general, seems confusing.

**Comment by hsluoyz** [comment]
`Or remove scroll and make it paginated after with like 10 rows per page.`

This would be good.
