### ISSUE TITLE
Error in go get github.com/casbin/casbin-dashboard

### ISSUE THREAD

**Issue by GermaVinsmoke** [casbin/casbin-dashboard#37]
On running `go get github.com/casbin/casbin-dashboard`, I'm getting this -

```
# github.com/casbin/casbin-dashboard/object
..\..\..\..\go\src\github.com\casbin\casbin-dashboard\object\adapter.go:64:36: 
ormManager.engine.Id undefined 
(type *xorm.Engine has no field or method Id, but does have ID)
..\..\..\..\go\src\github.com\casbin\casbin-dashboard\object\model.go:62:36: 
ormManager.engine.Id undefined 
(type *xorm.Engine has no field or method Id, but does have ID)
```

**Comment by rak-shit** [comment]
I am also facing with the same problem. Did you find any solution to this?

**Comment by devabhixda** [comment]
https://github.com/casbin/casbin-dashboard/issues/42#issuecomment-601999094 . @hsluoyz this can be closed.

**Comment by kjain0073** [comment]
@GermaVinsmoke I think you are running this command outside your local repo? If yes, you need to first
`cd casbin-dashboard`
then enter 
`go get github.com/casbin/casbin-dashboard`
I had a similar error and this was the case.I hope it works for you too!
