### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by hqm19** [casbin/casbin-dashboard#42]
object/policy.go:37:9: assignment mismatch: 2 variables but xormadapter.NewAdapter returns 1 values
object/policy.go:73:9: assignment mismatch: 2 variables but xormadapter.NewAdapter returns 1 values
object/policy.go:78:12: undefined: model.NewModelFromString
object/policy.go:83:9: assignment mismatch: 2 variables but casbin.NewEnforcer returns 1 values
object/policy.go:121:11: assignment mismatch: 2 variables but e.AddPolicy returns 1 values
object/policy.go:123:11: assignment mismatch: 2 variables but e.AddGroupingPolicy returns 1 values
object/policy.go:147:9: assignment mismatch: 2 variables but e.AddPolicy returns 1 values
object/policy.go:163:9: assignment mismatch: 2 variables but e.RemovePolicy returns 1 values

**Comment by shakti97** [comment]
Hi @hqm19 , can you please elaborate the steps you had taken and found this error. Would love to help

**Comment by devabhixda** [comment]
Please let us know the details of the issue and steps to reproduce the error so that we can look into it.

**Comment by kjain0073** [comment]
hi @shakti97 @devabhixda , this error comes right after 
`go get github.com/casbin/casbin-dashboard`
as you run
`go run main.go`
Kindly look into the issue as early as possible.

**Comment by devabhixda** [comment]
> hi @shakti97 @devabhixda , this error comes right after
> `go get github.com/casbin/casbin-dashboard`
> as you run
> `go run main.go`
> Kindly look into the issue as early as possible.

This was an issue with new version of xorm and has recently been fixed by https://github.com/casbin/casbin-dashboard/commit/dcc11957e179afe8842f3b4d9df687969e4642a6 , kindly get your local clone up streamed with the current changes.

**Comment by hsluoyz** [comment]
Fixed.

**Comment by kjain0073** [comment]
@hsluoyz @devabhixda thanks a lot!
