### ISSUE TITLE
unable to run it locally

### ISSUE THREAD

**Issue by tushar22-tg** [casbin/casbin-dashboard#51]
![Capture](https://user-images.githubusercontent.com/52567960/75974388-b1718d80-5efc-11ea-82c6-f63bad25e74c.PNG)

i am facing this issue while running development mode

**Comment by alekhgupta1441** [comment]
I too am facing this issue

**Comment by romitkarmakar** [comment]
Same issue here...Please look into this.

**Comment by devabhixda** [comment]
This might not be a proper solution but it looks these is some issue with go orm manager i.e. xorm. Try manually getting xorm `go get github.com/go-xorm/xorm`

**Comment by hsluoyz** [comment]
New version Xorm has broken its API. I enabled Go modules and lock down Xorm version to a previous working version: https://github.com/casbin/casbin-dashboard/commit/dcc11957e179afe8842f3b4d9df687969e4642a6
