### ISSUE TITLE
Proposal: Migrate to Typescript, Add Lint tool

### ISSUE THREAD

**Issue by ttzztztz** [casbin/casbin-dashboard#57]
If we migrate the frontend to the typescript, it will be easier to maintain in the future. A lot of errors caused by type error will be avoided. It is easy to migrate to typescript when at the beginning.

We should also add Lint tool to make the code in a better quality. For example: We should have a uniform usage of singal quote or double quote.
For example, The Pull Request #35 is not a good pull request, I think. Because it mixed the usage of ` " ` and ` ' `, it will mess up the codebase. To avoid this, I think that we should use some lint tool with strict rules.

I would like to work on it if this proposal is accepted.

**Comment by ttzztztz** [comment]
@hsluoyz

**Comment by hsluoyz** [comment]
Do not try to make an opinionated & controversial decision like JS or TS before contributing any concrete code. A beginner should proceed instead of steering.

You can try the pinned issues, which are suitable for first-time contributors: https://github.com/casbin/casbin-dashboard/issues
