### ISSUE TITLE
Footer should be fixed in the bottom of User ViewPort

### ISSUE THREAD

**Issue by aryamanpuri** [casbin/casbin-dashboard#6]
**Description**
 As the footer in the middle of page, should be fixed.

![Screenshot from 2020-02-21 17-33-11](https://user-images.githubusercontent.com/43513114/75033340-b122cc80-54d0-11ea-9b7c-627ee85f68b5.png)

**Additional Information**
I am working on this

**Comment by devabhixda** [comment]
@hsluoyz this can now be closed. Ref https://github.com/casbin/casbin-dashboard/pull/8#pullrequestreview-372666586

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casbin-dashboard/commit/c823377bd2c260f0cfab361ef1d0bdf405d13036
