### ISSUE TITLE
On starting the React App , there is some fixable warnings

### ISSUE THREAD

**Issue by aryamanpuri** [casbin/casbin-dashboard#7]
It should be fixed

![Screenshot from 2020-02-21 17-54-00](https://user-images.githubusercontent.com/43513114/75034490-4f179680-54d3-11ea-86bc-72adf111b1cf.png)

**Additional Information**
I am working on this

**Comment by devabhixda** [comment]
@hsluoyz PR has been merged, issue can be marked as resolved and be closed.
