### ISSUE TITLE
Problem with xorm when install

### ISSUE THREAD

**Issue by quocanh1897** [casbin/casbin-dashboard#73]
Hello, I have an error when installing the casbin-dashboard like this:

```
$ go get github.com/casbin/casbin-dashboard

# github.com/casbin/casbin-dashboard/object
go/src/github.com/casbin/casbin-dashboard/object/adapter.go:64:36: ormManager.engine.Id undefined (type *xorm.Engine has no field or method Id, but does have ID)
go/src/github.com/casbin/casbin-dashboard/object/model.go:62:36: ormManager.engine.Id undefined (type *xorm.Engine has no field or method Id, but does have ID)
```

Can you help me to solve this? Thanks.

**Comment by hsluoyz** [comment]
Your Xorm version is too new. We used Go Modules: https://github.com/casbin/casbin-dashboard/blob/master/go.mod to lock an old version Xorm. Please use Go Modules to update your dependency.

You can also choose to make a PR to fix the error with latest version Xorm.
