### ISSUE TITLE
The width of adapterTable has not been fixed to full-width

### ISSUE THREAD

**Issue by 438561537** [casbin/casbin-dashboard#74]
The width of Refactor Table has been fixed once[Link](https://github.com/casbin/casbin-dashboard/commit/c81546d8ebd70ed4d6d6e91ced471b883d663a00)， but forgot to fix the width of adapterTable.
https://github.com/casbin/casbin-dashboard/blob/c81546d8ebd70ed4d6d6e91ced471b883d663a00/web/src/AdapterTable.js#L157
![screem](https://user-images.githubusercontent.com/41043187/85095208-594c6600-b223-11ea-8620-f65c474c5aef.png)

**Comment by hsluoyz** [comment]
@438561537 can you make a PR?

**Comment by 438561537** [comment]
OK




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yang Luo"<notifications@github.com&gt;; 
发送时间: 2020年6月19日(星期五) 下午2:08
收件人: "casbin/casbin-dashboard"<casbin-dashboard@noreply.github.com&gt;; 
抄送: "438561537"<438561537@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [casbin/casbin-dashboard] The width of adapterTable has not been fixed to full-width (#74)





 
@438561537 can you make a PR?

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casbin/casbin-dashboard/pull/76
