### ISSUE TITLE
"Made with ❤️ by Casbin"  is at centre of the screen which should be at bottom.

### ISSUE THREAD

**Issue by chetan-v** [casbin/casbin-dashboard#75]
**Actual Behaviour**

![Screenshot from 2020-06-19 09-26-48](https://user-images.githubusercontent.com/63091769/85095510-36b05200-b20f-11ea-92a2-5c77153c5d8b.png)

![Screenshot from 2020-06-19 09-26-50](https://user-images.githubusercontent.com/63091769/85095568-63fd0000-b20f-11ea-9b18-a9bef66a89f4.png)

**Expected Behaviour**

It should be at bottom

**Comment by hsluoyz** [comment]
Please fix it.

**Comment by chetan-v** [comment]
> Please fix it.

ok do that
