### ISSUE TITLE
Optimize the UI

### ISSUE THREAD

**Issue by 438561537** [casbin/casbin-dashboard#80]
### Current Style:
The current layout and typegraphy cannot support the visualization of backend data, user management , modifying the wrong Casbin model and other functions. 

### Expected Style:
1. Change the frontend style for better interaction and the beautifying the UI.
2. Add the user management model to prevent illegal users whose behavior may disturb the system.

**Comment by hsluoyz** [comment]
@BetaCat0 can we ask the student to fix it?

**Comment by BetaCat0** [comment]
@hsluoyz Actually he is the student you mentioned :)

**Comment by hsluoyz** [comment]
Lol, that's great! Let's do it :)
