### ISSUE TITLE
Typo in Readme

### ISSUE THREAD

**Issue by arteevraina** [casbin/casbin-dashboard#92]
While the React's client-side port runs on port 3000 but in the readme, it has been mentioned that it runs on port 3030.

Additional Information:
I will make a PR for this.

**Comment by BetaCat0** [comment]
Yes, please 👍

**Comment by arteevraina** [comment]
@BetaCat0 Sure thing.

**Comment by hsluoyz** [comment]
@arteevraina it runs on 3030:

https://github.com/casbin/casbin-dashboard/blob/7851225732e602626eab7c95a57eea8967542539/web/package.json#L18-L23

**Comment by arteevraina** [comment]
@hsluoyz But the logs say something like this :

```
Compiled successfully!

You can now view web in the browser.

  Local:            http://localhost:3000/
  On Your Network:  http://192.168.1.8:3000/

Note that the development build is not optimized.
To create a production build, use npm run build.
```
Correct me if I am wrong.

**Comment by hsluoyz** [comment]
It's because of OS.

**Comment by arteevraina** [comment]
> It's because of OS.

ok, thanks :)
