### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by andyyumiao** [casbin/casbin-dashboard#95]
panic: dial tcp 127.0.0.1:3306: connect: connection refused

goroutine 1 [running]:
github.com/casbin/casbin-dashboard/object.(*OrmManager).open(0xc0001a86c0)
	/Users/yumiao3/workspace/github/casbin-dashboard/object/orm_manager.go:60 +0x133
github.com/casbin/casbin-dashboard/object.NewOrmManager(0x173bce1, 0x5, 0xc0000cc380, 0x1e, 0x1e)
	/Users/yumiao3/workspace/github/casbin-dashboard/object/orm_manager.go:39 +0x7d
github.com/casbin/casbin-dashboard/object.InitOrmManager()
	/Users/yumiao3/workspace/github/casbin-dashboard/object/orm_manager.go:14 +0x73
main.main()
	/Users/yumiao3/workspace/github/casbin-dashboard/main.go:13 +0x26

**Comment by arteevraina** [comment]
Yes, I am also getting same error on starting server.

**Comment by andyyumiao** [comment]
> Yes, I am also getting same error on starting server.

you may run 'go get' command before startup:
go get github.com/astaxie/beego
go get "github.com/astaxie/beego/plugins/cors"
go get "github.com/casbin/casbin-dashboard/object"
go get "github.com/casbin/casbin-dashboard/routers"

**Comment by hsluoyz** [comment]
@andyyumiao please setup your DB connection string: https://github.com/casbin/casbin-dashboard#installation

**Comment by arteevraina** [comment]
@hsluoyz I am getting the same error after following the above-mentioned steps.

Logs - 
```
panic: dial tcp 127.0.0.1:3306: connect: connection refused

goroutine 1 [running]:
github.com/casbin/casbin-dashboard/object.(*OrmManager).open(0xc00022d5f0)
        /home/arteev/casbin-dashboard/object/orm_manager.go:60 +0x131
github.com/casbin/casbin-dashboard/object.NewOrmManager(0xc761a6, 0x5, 0xc0000db000, 0x1d, 0x1d)
        /home/arteev/casbin-dashboard/object/orm_manager.go:39 +0x7d
github.com/casbin/casbin-dashboard/object.InitOrmManager()
        /home/arteev/casbin-dashboard/object/orm_manager.go:14 +0x73
main.main()
        /home/arteev/casbin-dashboard/main.go:13 +0x26
exit status 2
```
Are there any other workarounds?

**Comment by arteevraina** [comment]
@andyyumiao Were you able to fix this?

**Comment by hsluoyz** [comment]
Did you have installed a DB like MySQL at: 127.0.0.1:3306 ?

**Comment by andyyumiao** [comment]
rubbish, get out of GitHub!!!

**Comment by china78** [comment]
> rubbish, get out of GitHub!!!

shut fuck up niger!
